mapa_sector_inverso = {
    "Alto Mochica": 0,
    "Aranjuez": 1,
    "Arboleda - Galenos": 2,
    "Centro Cívico Norte": 3,
    "Centro Cívico Sur": 4,
    "Chicago": 5,
    "Cortijo": 6,
    "Covicorti I": 7,
    "Covicorti Ii": 8,
    "Daniel Hoyle": 9,
    "El Alambre": 10,
    "El Bosque": 11,
    "El Molino": 12,
    "El Recreo": 13,
    "Gran Chimù": 14,
    "Granados": 15,
    "Huerta Grande": 16,
    "Jorge Chavez": 17,
    "La Marqueza": 18,
    "La Merced": 19,
    "La Noria": 20,
    "La Rinconada": 21,
    "Las Causuarinas": 22,
    "Libertad": 23,
    "Los Jazmines": 24,
    "Los Laureles": 25,
    "Los Pinos": 26,
    "Los Portales": 27,
    "Los Rosales De San Andres": 28,
    "Miraflores": 29,
    "Monserrate": 30,
    "Natasha Alta": 31,
    "Palermo Norte": 32,
    "Palermo Sur": 33,
    "Pay Pay": 34,
    "P.J. El Bosque": 35,
    "P.J.El Bosque": 36,
    "Pesqueda": 37,
    "Primavera": 38,
    "Quintanas I": 39,
    "Quintanas Ii": 40,
    "Quintanas Iv": 41,
    "Quintanas V": 42,
    "Razuri": 43,
    "San Andrés": 44,
    "San Fernando": 45,
    "San Isidro": 46,
    "San Nícolas": 47,
    "Sánchez Carríon": 48,
    "Santa Teresa De Avila": 49,
    "Sta Inés": 50,
    "Sta Isabel": 51,
    "Sta María": 52,
    "Sta Sofía": 53,
    "Sto.Dominguito": 54,
    "Torres Araujo": 55,
    "Trupal": 56,
    "Urb. Chimu": 57,
    "Villa De Contadores": 58,
    "Vista Hermosa": 59,
    "Virgen De La Puerta": 60
}

sector_a_zona = {
    # Alambre
    "Los Pinos": "Alambre",
    "Alto Mochica": "Alambre",
    "Razuri": "Alambre",
    "Torres Araujo": "Alambre",
    "El Molino": "Alambre",
    "Covicorti I": "Alambre",
    "San Nícolas": "Alambre",
    "San Isidro": "Alambre",
    "Sánchez Carríon": "Alambre",
    "Primavera": "Alambre",
    "Sta Inés": "Alambre",
    "Jorge Chavez": "Alambre",
    "Palermo Sur": "Alambre",
    "Sta Isabel": "Alambre",
    "Cortijo": "Alambre",
    "San Fernando": "Alambre",
    "Vista Hermosa": "Alambre",
    "Trupal": "Alambre",
    "Covicorti Ii": "Alambre",
    "Aranjuez": "Alambre",
    "Chicago": "Alambre",
    "Virgen De La Puerta": "Alambre",
    "Los Rosales De San Andres": "Alambre",
    "Natasha Alta": "Alambre",
    "El Alambre": "Alambre",
    "San Andrés": "Alambre",
    "Quintanas I": "Alambre",
    "Villa De Contadores": "Alambre",
    "Miraflores": "Alambre",
    "Santa Teresa De Avila": "Alambre",
    "Gran Chimù": "Alambre",
    "Huerta Grande": "Alambre",
    "Daniel Hoyle": "Alambre",
    "Urb. Chimu": "Alambre",
    "Sta María": "Alambre",
    "Las Causuarinas": "Alambre",
    "Monserrate": "Alambre",
    "La Merced": "Alambre",
    "Sto.Dominguito": "Alambre",
    "Centro Cívico Norte": "Alambre",
    "El Recreo": "Alambre",
    "P.J.El Bosque": "Alambre",
    "El Bosque": "Alambre",
    "Pesqueda": "Alambre",
    "Quintanas V": "Alambre",
    "Centro Cívico Sur": "Alambre",
    "Palermo Norte": "Alambre",
    "Quintanas Ii": "Alambre",
    "La Rinconada": "Alambre",
    "Arboleda - Galenos": "Alambre",
    "Los Portales": "Alambre",
    "Granados": "Alambre",
    "Quintanas Iv": "Alambre",
    "La Noria": "Alambre",
    "La Marqueza": "Alambre",
    "Los Jazmines": "Alambre",
    "P.J. El Bosque": "Alambre",
    "Los Laureles": "Alambre",
    "Pay Pay": "Alambre",
    "Libertad": "Alambre",
    "Chicago": "Ayacucho",
    "Monserrate": "Ayacucho",
    "Torres Araujo": "Ayacucho",
    "Centro Cívico Norte": "Ayacucho",
    "Sta María": "Ayacucho",
    "Palermo Sur": "Ayacucho",
    "Centro Cívico Sur": "Ayacucho",
    "San Andrés": "Ayacucho",
    "Arboleda - Galenos": "Ayacucho",
    "Gran Chimù": "Ayacucho",
    "Los Jazmines": "Ayacucho",
    "Quintanas I": "Ayacucho",
    "La Merced": "Ayacucho",
    "Los Laureles": "Ayacucho",
    "El Recreo": "Ayacucho",
    "Las Causuarinas": "Ayacucho",
    "Villa De Contadores": "Ayacucho",
    "P.J.El Bosque": "Ayacucho",
    "Sto.Dominguito": "Ayacucho",
    "El Molino": "Noria",
    "Palermo Sur": "Noria",
    "La Noria": "Noria",
    "Aranjuez": "Noria",
    "Palermo Norte": "Noria",
    "Daniel Hoyle": "Noria",
    "Sto.Dominguito": "Noria",
    "La Rinconada": "Noria",
    "Santa Teresa De Avila": "Noria",
    "Urb. Chimu": "Noria",
    "Los Portales": "Noria",
    "Quintanas Ii": "Noria",
    "Razuri": "Noria",
    "Granados": "Noria",
    "Quintanas Iv": "Noria",
    "Huerta Grande": "Noria",
    "Miraflores": "Noria",
    "Quintanas V": "Noria",
    "Quintanas I": "Noria",
    "El Bosque": "Noria",
    "Pesqueda": "Noria",
    "P.J. El Bosque": "Noria",
    "La Marqueza": "Noria",
    "Pay Pay": "Noria",
    "Sta Sofía": "Noria",
    "Libertad": "Noria"
}

mapa_zona_inverso = {
    "Alambre": 0,
    "Ayacucho": 1,
    "Noria": 2
}

mapa_grupo_incidente  = {
    0: "Actos Obsenos",
    1: "Alteración del orden en vía pública",
    2: "Ambiente y limpieza",
    3: "Animales",
    4: "Apoyo y asistencia",
    5: "Consumo de sustancias",
    6: "Emergencias",
    7: "Escándalo público",
    8: "Incidentes escolares",
    9: "Obstrucción vía pública",
    10: "Robos",
    11: "Seguridad ciudadana",
    12: "Tránsito",
    13: "Violencia"
}
